api:
    token: ''
autotester:
    code: ''
    url: http://localhost:7071/api/orchestrators/orchestrator
blobstorage:
    account: account
    connection: DefaultEndpointsProtocol=https;AccountName=account;AccountKey=key;EndpointSuffix=example.com
    container: container
    eksternalhost: localhost
    sasttl: 3600000
crawler:
    code: ''
    url:
kravregister:
    host: http://localhost:8082
loeysingsregister:
    host: http://localhost:8000
rapportVerktoey:
    host: http://localhost:8084
server:
    error:
        include-stacktrace: never
spring:
    config:
        import: optional:classpath:./dev.properties
    datasource:
        hikari:
            schema: testlab2_testing
        password:
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=testlab2_testing
        username:
    flyway:
        schemas: testlab2_testing
    security:
        oauth2:
            client:
                provider:
                    brukar:
                        issuer-uri: ''
                registration:
                    brukar:
                        client-id: ''
                        client-name: ''
                        client-secret: ''
                        scope: openid,profile
            resourceserver:
                jwt:
                    issuer-uri:
    servlet:
        multipart:
            enabled: true
            max-file-size: 2MB
            max-request-size: 2MB
    sql:
        init:
            platform: postgresql
springdoc:
    swagger-ui:
        path: /api-dokumentasjon
