name: Deploy Prod

on:
  workflow_dispatch:
    inputs:
      git_sha:
        description: 'Git commit'
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  login:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: login

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ca-ddt-testlab2-prod-testing -g RG-DDT-Testlab2-prod --server ${{ secrets.ACR_ENDPOINT }} --username  ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
            az containerapp update -n ca-ddt-testlab2-prod-testing -g RG-DDT-Testlab2-prod --image acrddtprod.azurecr.io/testlab2-testing:${{ github.event.inputs.git_sha }} --subscription ${{ secrets.SUBSCRIPTION_ID }}
